<?php
$articleSearch=trim((string)($_GET['article_q']??''));$articleStatus=(string)($_GET['status']??'all');$articleSort=(string)($_GET['sort']??'newest');$articlePage=max(1,(int)($_GET['page']??1));
$editId=(int)($_GET['edit']??0);$editing=$editId?$Articles->find($editId):null;$news=$Articles->adminList($articleSearch,$articleStatus,$articleSort,20,($articlePage-1)*20);
?>
<div class="ap-title"><div><span>Publications du CMS</span><h1>Articles</h1></div><a class="ap-button" href="?tab=articles">Nouvel article</a></div>
<form class="ap-filters" method="get"><input type="hidden" name="tab" value="articles"><input name="article_q" placeholder="Rechercher un titre ou un slug…" value="<?= adm_e($articleSearch) ?>"><select name="status"><option value="all">Tous les statuts</option><option value="published" <?= $articleStatus==='published'?'selected':'' ?>>Publiés</option><option value="draft" <?= $articleStatus==='draft'?'selected':'' ?>>Brouillons</option></select><select name="sort"><option value="newest">Plus récents</option><option value="oldest" <?= $articleSort==='oldest'?'selected':'' ?>>Plus anciens</option></select><button>Filtrer</button></form>
<section class="ap-grid article-admin-grid">
<form class="ap-panel article-editor" method="post" enctype="multipart/form-data"><?= admin_csrf() ?><input type="hidden" name="action" value="article_save"><input type="hidden" name="id" value="<?= (int)($editing['id']??0) ?>"><input type="hidden" name="existing_image" value="<?= adm_e($editing['image_url']??'') ?>"><h2><?= $editing?'Modifier l’article':'Créer un article' ?></h2><label>Titre<input name="title" maxlength="160" required value="<?= adm_e($editing['title']??'') ?>"></label><label>Petite description<textarea name="summary" maxlength="300" rows="3"><?= adm_e($editing['summary']??'') ?></textarea></label><label>Image de couverture<input type="file" name="cover" accept="image/jpeg,image/png,image/webp,image/gif"></label><?php if(!empty($editing['image_url'])):?><img class="article-cover-preview" src="<?= adm_e(URL.'/'.$editing['image_url']) ?>" alt=""><?php endif?><div class="article-toolbar"><button type="button" data-tag="strong"><b>Gras</b></button><button type="button" data-tag="em"><i>Italique</i></button><button type="button" data-tag="h2">Titre</button><button type="button" data-tag="p">Paragraphe</button><button type="button" data-tag="ul">Liste</button><button type="button" data-link>Lien</button></div><label>Contenu<textarea id="article-content" name="content" rows="14" required><?= adm_e($editing['content']??'') ?></textarea></label><label>Statut<select name="status"><option value="draft">Brouillon</option><option value="published" <?= !empty($editing['published'])?'selected':'' ?>>Publié</option></select></label><label>Date de publication<input type="datetime-local" name="published_at" value="<?= !empty($editing['published_at'])?date('Y-m-d\TH:i',(int)$editing['published_at']):date('Y-m-d\TH:i') ?>"></label><button data-confirm="Enregistrer cet article ?"><?= $editing?'Enregistrer les modifications':'Créer l’article' ?></button></form>
<div class="ap-panel ap-wide"><h2>Liste des articles</h2><div class="ap-table"><table><thead><tr><th>Titre</th><th>Auteur</th><th>Statut</th><th>Création</th><th>Publication</th><th></th></tr></thead><tbody><?php while($n=mysqli_fetch_assoc($news)):?><tr><td><b><?= adm_e($n['title']) ?></b><small>/article/<?= adm_e($n['slug']) ?></small></td><td><?= adm_e($n['author_name']??'Inconnu') ?></td><td><span class="ap-badge <?= $n['published']?'green':'' ?>"><?= $n['published']?'Publié':'Brouillon' ?></span></td><td><?= adm_date($n['created_at']) ?></td><td><?= $n['published']?adm_date($n['published_at']):'—' ?></td><td><div class="article-row-actions"><a class="ap-button small" href="?tab=articles&edit=<?= (int)$n['id'] ?>">Modifier</a><?php if($n['published']):?><a class="ap-button small" target="_blank" href="<?= adm_e(URL.'/article/'.$n['slug']) ?>">Voir</a><?php endif?><?php if((int)$UData['rank']>=6):?><form method="post"><?= admin_csrf() ?><input type="hidden" name="action" value="article_delete"><input type="hidden" name="id" value="<?= (int)$n['id'] ?>"><button class="small danger" data-confirm="Êtes-vous sûr de vouloir supprimer cet article ?">Supprimer</button></form><?php endif?></div></td></tr><?php endwhile?></tbody></table></div><div class="ap-pages"><?php if($articlePage>1):?><a href="?tab=articles&page=<?= $articlePage-1 ?>">← Précédent</a><?php endif?><span>Page <?= $articlePage ?></span><a href="?tab=articles&page=<?= $articlePage+1 ?>">Suivant →</a></div></div>
</section>
<script>document.querySelectorAll('.article-toolbar [data-tag]').forEach(function(b){b.addEventListener('click',function(){var t=document.getElementById('article-content'),tag=b.dataset.tag,s=t.selectionStart,e=t.selectionEnd,v=t.value.slice(s,e)||'Texte',open='<'+tag+'>',close='</'+tag+'>';if(tag==='ul'){open='<ul><li>';close='</li></ul>'}t.setRangeText(open+v+close,s,e,'end');t.focus()})});var lb=document.querySelector('.article-toolbar [data-link]');if(lb)lb.addEventListener('click',function(){var t=document.getElementById('article-content'),url=prompt('Adresse du lien (https://…)');if(!url)return;var s=t.selectionStart,e=t.selectionEnd,v=t.value.slice(s,e)||'Lien';t.setRangeText('<a href="'+url.replace(/"/g,'')+'">'+v+'</a>',s,e,'end')});</script>
