## MySQL Configuration
db.hostname=127.0.0.1
db.port=3306
db.username=root
db.password=
db.name=waveplus

## MySQL pooling setup (controls amount of connections)
db.pool.minsize=5
db.pool.maxsize=65

## Game TCP/IP Configuration
game.tcp.bindip=0.0.0.0
game.tcp.port=2096
game.tcp.conlimit=100000
game.tcp.conperip=50000
game.tcp.enablenagles=true

## MUS TCP/IP Configuration
rcon.tcp.bindip=127.0.0.1
rcon.tcp.port=30001
rcon.tcp.allowedaddr=localhost;127.0.0.1

## Client configuration
client.ping.enabled=1
client.ping.interval=30000
client.maxrequests=300

## Redis Configuration
redis.enabled=0
redis.hostname=127.0.0.1
redis.port=6379
redis.password=
redis.database=0

## Roleplay
## Where pre-rendered group badges are served from. %badge% is replaced with the badge code.
group.badge.url=https://paradiserp.fr/swf_pz/V5-0-2/c_images/Badgeparts/%badge%.png

## DotNetty threading
game.tcp.acceptGroupThreads=2
game.tcp.ioGroupThreads=4
game.tcp.channelGroupThreads=4