-- French localization for the active WaveRP stack.
-- Technical identifiers (keys, job names, permissions and interaction types) stay unchanged.
SET NAMES utf8mb4;

UPDATE jobs SET display_name = 'Sans emploi', description = 'Aucun emploi actuel' WHERE name = 'unemployed';
UPDATE jobs SET display_name = 'Police nationale', description = 'Forces de l''ordre et sécurité publique' WHERE name = 'police';
UPDATE jobs SET display_name = 'EMS - Services médicaux', description = 'Soins, urgences et transport médical' WHERE name = 'hospital';
UPDATE jobs SET display_name = 'Café', description = 'Préparation et vente de boissons et repas' WHERE name = 'starbucks';
UPDATE jobs SET display_name = 'Armurerie', description = 'Vente d''armes et d''équipements de protection' WHERE name = 'armory';
UPDATE jobs SET display_name = 'Casino', description = 'Jeux, accueil et gestion du casino' WHERE name = 'casino';
UPDATE jobs SET display_name = 'Banque', description = 'Services bancaires et gestion des comptes' WHERE name = 'bank';

UPDATE job_ranks SET display_name = 'Sans emploi' WHERE name = 'unemployed';
UPDATE job_ranks SET display_name = 'Cadet de police' WHERE name = 'police_cadet';
UPDATE job_ranks SET display_name = 'Agent de police' WHERE name = 'police_officer';
UPDATE job_ranks SET display_name = 'Sergent de police' WHERE name = 'police_sergeant';
UPDATE job_ranks SET display_name = 'Lieutenant de police' WHERE name = 'police_lieutenant';
UPDATE job_ranks SET display_name = 'Capitaine de police' WHERE name = 'police_captain';
UPDATE job_ranks SET display_name = 'Commissaire de police' WHERE name = 'police_chief';
UPDATE job_ranks SET display_name = 'Infirmier' WHERE name = 'hospital_nurse';
UPDATE job_ranks SET display_name = 'Médecin urgentiste' WHERE name = 'hospital_supervisor';
UPDATE job_ranks SET display_name = 'Ambulancier superviseur' WHERE name = 'hospital_asst_manager';
UPDATE job_ranks SET display_name = 'Directeur des services médicaux' WHERE name = 'hospital_manager';
UPDATE job_ranks SET display_name = 'Barista' WHERE name = 'starbucks_barista';
UPDATE job_ranks SET display_name = 'Responsable d''équipe' WHERE name = 'starbucks_supervisor';
UPDATE job_ranks SET display_name = 'Directeur adjoint' WHERE name = 'starbucks_asst_manager';
UPDATE job_ranks SET display_name = 'Directeur du café' WHERE name = 'starbucks_manager';
UPDATE job_ranks SET display_name = 'Vendeur' WHERE name = 'armory_sales';
UPDATE job_ranks SET display_name = 'Responsable d''équipe' WHERE name = 'armory_supervisor';
UPDATE job_ranks SET display_name = 'Directeur adjoint' WHERE name = 'armory_asst_manager';
UPDATE job_ranks SET display_name = 'Directeur de l''armurerie' WHERE name = 'armory_manager';
UPDATE job_ranks SET display_name = 'Croupier' WHERE name = 'casino_dealer';
UPDATE job_ranks SET display_name = 'Responsable de salle' WHERE name = 'casino_supervisor';
UPDATE job_ranks SET display_name = 'Directeur adjoint' WHERE name = 'casino_asst_manager';
UPDATE job_ranks SET display_name = 'Directeur du casino' WHERE name = 'casino_manager';
UPDATE job_ranks SET display_name = 'Guichetier' WHERE name = 'bank_teller';
UPDATE job_ranks SET display_name = 'Responsable d''équipe' WHERE name = 'bank_supervisor';
UPDATE job_ranks SET display_name = 'Directeur adjoint' WHERE name = 'bank_asst_manager';
UPDATE job_ranks SET display_name = 'Directeur de la banque' WHERE name = 'bank_manager';

UPDATE crimes SET name = 'Meurtre', notes = 'Meurtre d''un joueur qui n''appartient pas à une organisation' WHERE id = 1;
UPDATE crimes SET name = 'Homicide entre gangs', notes = 'Le meurtrier et la victime appartiennent à une organisation' WHERE id = 2;
UPDATE crimes SET name = 'Exécution', notes = 'Meurtre d''un joueur menotté' WHERE id = 3;
UPDATE crimes SET name = 'Braquage', notes = 'Tentative ou réussite d''un braquage de caisse, coffre ou autre cible' WHERE id = 4;
UPDATE crimes SET name = 'Meurtres multiples', notes = 'Meurtre commis par une personne déjà recherchée' WHERE id = 5;
UPDATE crimes SET name = 'Meurtre d''un policier', notes = 'Meurtre d''un policier en service' WHERE id = 6;
UPDATE crimes SET name = 'Fuite par déconnexion', notes = 'Déconnexion pendant une escorte policière' WHERE id = 7;
UPDATE crimes SET name = 'Agression', notes = 'Agression d''un autre joueur' WHERE id = 8;
UPDATE crimes SET name = 'Abus du 911', notes = 'Utilisation abusive ou mensongère du service 911' WHERE id = 9;
UPDATE crimes SET name = 'Entrave à la justice', notes = 'Agression d''un joueur escorté par la police' WHERE id = 10;
UPDATE crimes SET name = 'Agression d''un policier', notes = 'Agression d''un policier en service' WHERE id = 11;

INSERT INTO emulator_settings (`key`, `value`) VALUES
('commands.cmd_911.keys', 'aide;911;help;callpolice'),
('commands.cmd_accept_offer.keys', 'accepteroffre;acceptoffer'),
('commands.cmd_apply.keys', 'utiliser;apply'),
('commands.cmd_arrest.keys', 'arreterpolice;arrest;jail'),
('commands.cmd_balance.keys', 'solde;balance'),
('commands.cmd_bucks.keys', 'argent;bucks'),
('commands.cmd_charge.keys', 'inculper;charge'),
('commands.cmd_clear_offer.keys', 'effaceroffres;clearoffers'),
('commands.cmd_combat_stats.keys', 'combat;combat_stats'),
('commands.cmd_decline_offer.keys', 'refuseroffre;declineoffer'),
('commands.cmd_demote.keys', 'retrograder;demote'),
('commands.cmd_deposit.keys', 'depot;deposit'),
('commands.cmd_equip.keys', 'equiper;equip'),
('commands.cmd_escort.keys', 'escorter;escort'),
('commands.cmd_fire.keys', 'licencier;fire'),
('commands.cmd_give.keys', 'virement;give'),
('commands.cmd_global_heal.keys', 'soignertous;global_heal'),
('commands.cmd_goto_room.keys', 'allersalle;goto_room'),
('commands.cmd_heal.keys', 'soigner;heal'),
('commands.cmd_hire.keys', 'recruter;hire'),
('commands.cmd_hit.keys', 'frapper;hit'),
('commands.cmd_hotrooms.keys', 'salles;hotrooms;hot'),
('commands.cmd_make_territory.keys', 'creerterritoire;territory;create_territory'),
('commands.cmd_offer_rpitem.keys', 'proposer;offer'),
('commands.cmd_openaccount.keys', 'ouvrircompte;openaccount'),
('commands.cmd_org_create.keys', 'creerorganisation;create;create_organization'),
('commands.cmd_org_delete.keys', 'supprimerorganisation;delete;disband;disband_organization'),
('commands.cmd_org_invite.keys', 'inviterorganisation;recruit;invite_organization'),
('commands.cmd_org_join.keys', 'rejoindreorganisation;join_organization;join'),
('commands.cmd_org_kick.keys', 'exclureorganisation;remove;kick_organization'),
('commands.cmd_org_leave.keys', 'quitterorganisation;leave;leave_organization'),
('commands.cmd_org_rankdown.keys', 'retrograderorganisation;rankdown;rankdown_organization'),
('commands.cmd_org_rankup.keys', 'promouvoirorganisation;rankup;rankup_organization'),
('commands.cmd_org_rename.keys', 'renommerorganisation;rename;rename_organization'),
('commands.cmd_pardon.keys', 'gracier;pardon'),
('commands.cmd_passive.keys', 'passif;passive'),
('commands.cmd_promote.keys', 'promouvoir;promote'),
('commands.cmd_quit_job.keys', 'demissionner;quitjob'),
('commands.cmd_release.keys', 'liberer;release'),
('commands.cmd_rob.keys', 'braquer;rob'),
('commands.cmd_room_heal.keys', 'soignersalle;room_heal'),
('commands.cmd_room_release.keys', 'liberersalle;room_release'),
('commands.cmd_sell_rpitem.keys', 'vendre;sell'),
('commands.cmd_send_home.keys', 'renvoyer;sendhome'),
('commands.cmd_send_room.keys', 'envoyersalle;send_room'),
('commands.cmd_set_stats.keys', 'statistiques;set_stats'),
('commands.cmd_shoot.keys', 'tirer;shoot'),
('commands.cmd_spit.keys', 'cracher;spit'),
('commands.cmd_staff_arrest.keys', 'emprisonnerstaff;staff_arrest'),
('commands.cmd_staff_hit.keys', 'frapperstaff;staff_hit'),
('commands.cmd_staff_release.keys', 'libererstaff;staff_release'),
('commands.cmd_stopescort.keys', 'arreterescorte;stopescort'),
('commands.cmd_super_heal.keys', 'supersoin;super_heal'),
('commands.cmd_target_lock.keys', 'verrouillercible;locktarget;lt;lock'),
('commands.cmd_transactions.keys', 'transactions;history'),
('commands.cmd_unequip.keys', 'desequiper;unequip'),
('commands.cmd_wanted_list.keys', 'recherches;wanted_list'),
('commands.cmd_withdraw.keys', 'retirer;withdraw')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

INSERT INTO `emulator_texts` (`key`, `value`) VALUES
('essentials.buyroom.has_guild', 'Cette salle appartient a un groupe et ne peut pas etre achetee.'),
('essentials.cmd_brb.back', '* %username% est de retour ! *'),
('essentials.cmd_brb.brb', '* %username% est maintenant absent ! *'),
('essentials.cmd_brb.time', '* %username% est absent depuis %time% minute(s) *'),
('essentials.cmd_buildheight.invalid_height', 'Hauteur invalide ! Elle doit etre comprise entre 0 et 40.'),
('essentials.cmd_disable_effects.effects_disabled', 'Les effets ont ete desactives dans cette salle !'),
('essentials.cmd_disable_effects.effects_enabled', 'Les effets ont ete actives dans cette salle !'),
('essentials.cmd_explain.help', 'Indiquez une commande a consulter. Exemple : :explain mimic'),
('essentials.cmd_explain.info', 'Informations sur la commande %command% :\rUtilisation : %description%\rMots-cles et alias : %keys%'),
('essentials.cmd_explain.nopermission', 'Vous n''avez pas la permission d''utiliser %command%.'),
('essentials.cmd_explain.notfound', 'La commande %command% n''existe pas.'),
('essentials.cmd_hoverboard.texts', '* Prend un hoverboard bleu et s''envole *;* Monte sur un hoverboard rose *;* Profite de la journee sur un hoverboard jaune *;* Sort un hoverboard vert pour explorer l''hotel *'),
('essentials.cmd_pay.incorrect.usage', 'Parametres manquants pour la commande de paiement !'),
('essentials.cmd_pay.invalid_amount', 'Montant invalide ! Utilisez une valeur positive.'),
('essentials.cmd_pay.invalid_type', 'La monnaie %type% n''existe pas !'),
('essentials.cmd_pay.not_enough', 'Impossible de payer %username% : il vous manque %amount% %type% !'),
('essentials.cmd_pay.received', '%username% vous a verse %amount% %type% !'),
('essentials.cmd_pay.self', 'Vous ne pouvez pas vous payer vous-meme !'),
('essentials.cmd_pay.transferred', 'Vous avez verse %amount% %type% a %username% !'),
('essentials.cmd_set.invalid', 'Identifiant de meuble invalide : %value%.'),
('essentials.cmd_set.notfound', 'Meuble introuvable.'),
('essentials.cmd_slime.missed', '* Rate le visage de %username% *'),
('essentials.cmd_slime.slimed', '* Se fait couvrir de slime par %username% *'),
('essentials.cmd_slime.throws', '* Lance du slime vers %username% *'),
('essentials.cmd_welcome.text', 'Bienvenue a %username% sur %hotelname%;Je m''appelle %greeter_username% et je suis %greeter_rank% sur %hotelname%;Il y a actuellement %onlinecount% %hotelplayername%(s) en ligne !;Si vous avez des questions, adressez-vous a moi ou a un membre du staff reconnaissable a son badge;Bon sejour sur %hotelname%, %username% !'),
('essentials.nuke.action', '* Lance une bombe vers %username% *'),
('essentials.nuke.nuked', '* %username% est aneanti *'),
('essentials.nuke.self', 'Vous ne pouvez pas vous viser vous-meme !'),
('essentials.sellroom.buyroom.usage', 'Pour acheter cette salle, utilisez :%key% %confirmkey%.'),
('essentials.sellroom.confirmed', 'Cette salle est maintenant en vente pour %credits% credits !'),
('essentials.sellroom.forsale', 'Cette salle est vendue par %ownername% pour %credits% credits.'),
('essentials.sellroom.has_guild', 'Cette salle appartient a un groupe et ne peut pas etre vendue.'),
('essentials.sellroom.invalid_credits', '%credits% credits n''est pas un montant valide !'),
('essentials.sellroom.notforsale', 'Cette salle n''est pas en vente.'),
('essentials.sellroom.owneroffline', 'Le proprietaire de cette salle, %username%, est hors ligne.'),
('essentials.sellroom.removed', 'Cette salle a ete retiree de la vente.'),
('essentials.sellroom.selfbuy', '%username%, vous ne pouvez pas acheter votre propre salle.'),
('essentials.sellroom.usage', 'Utilisation : :sellroom <credits>'),
('furnidata.cmd_furnidata.off', 'Les donnees des meubles ont ete desactivees !'),
('furnidata.cmd_furnidata.on', 'Les donnees des meubles ont ete activees !'),
('rosie.buyroom.bubble.message', 'Cette salle a ete achetee a %oldowner% par %newowner% !'),
('rosie.buyroom.bubble.message.bought', '%roomname% a ete achetee par %newowner%.'),
('rosie.buyroom.has_guild', 'Cette salle appartient a un groupe et ne peut pas etre achetee.'),
('rosie.buyroom.invalid_amount', 'Vous n''avez pas assez de diamants pour acheter cette salle !'),
('rosie.roomforsale.alert', 'Cette salle est en vente. Saisissez :buyroom pour plus d''informations.'),
('rosie.sellroom.bubble.thisroom', 'Cette salle est en vente pour %currency% diamants !'),
('rosie.sellroom.buyroom.usage', 'Pour acheter cette salle, utilisez :%key% %confirmkey%.'),
('rosie.sellroom.confirmed', 'Cette salle est maintenant en vente pour %currency% diamants !'),
('rosie.sellroom.forsale', 'Cette salle est vendue par %ownername% pour %currency% diamants. Pour l''acheter, saisissez :buyroom confirm.'),
('rosie.sellroom.has_guild', 'Cette salle appartient a un groupe et ne peut pas etre vendue.'),
('rosie.sellroom.invalid_credits', '%diamonds% diamants n''est pas un montant valide !'),
('rosie.sellroom.notforsale', 'Cette salle n''est pas en vente.'),
('rosie.sellroom.owneroffline', 'Le proprietaire de cette salle, %username%, est hors ligne.'),
('rosie.sellroom.removed', 'Cette salle a ete retiree de la vente.'),
('rosie.sellroom.selfbuy', '%username%, vous ne pouvez pas acheter votre propre salle.'),
('rosie.sellroom.usage', 'Utilisation : :sellroom <diamants>'),
('scripter.warning.catalog.badge_display', '%username% a tente d''acheter un presentoir avec le badge %badge% qu''il ne possede pas !'),
('scripter.warning.catalog.count', '%username% a tente d''acheter plusieurs %itemname% sur la page %pagename% alors que les offres multiples sont desactivees !'),
('scripter.warning.catalog.page', '%username% a tente d''acceder sans autorisation a la page %pagename%.'),
('scripter.warning.chat.length', '%username% a tente d''envoyer un message de %length% caracteres alors que la limite est de 100.'),
('scripter.warning.guild.buy.owner', '%username% a tente d''acheter un groupe pour la salle %roomname% appartenant a %owner%.'),
('scripter.warning.item.bgtoner.permission', '%username% a tente de modifier la couleur de fond sans droits dans %room%, appartenant a %owner%.'),
('scripter.warning.look.gender', '%username% a tente d''utiliser le genre invalide %gender%.'),
('scripter.warning.marketplace.forbidden', '%username% a tente de vendre %itemname% pour %credits% alors que cet objet est interdit sur le marche !'),
('scripter.warning.modtools.alert', '%username% a tente d''envoyer une alerte sans acces aux outils de moderation : %message%.'),
('scripter.warning.modtools.ban', '%username% a tente de bannir un joueur sans autorisation depuis les outils de moderation !'),
('scripter.warning.modtools.chatlog', '%username% a demande un historique de discussion sans autorisation !'),
('scripter.warning.modtools.kick', '%username% a tente d''expulser un joueur sans autorisation depuis les outils de moderation !'),
('scripter.warning.modtools.roominfo', '%username% a demande les informations d''une salle sans autorisation !'),
('scripter.warning.modtools.roomsettings', '%username% a tente de modifier une salle sans autorisation depuis les outils de moderation !'),
('scripter.warning.modtools.ticket.close', '%username% a tente de fermer un ticket sans autorisation !'),
('scripter.warning.modtools.ticket.pick', '%username% a tente de prendre un ticket sans autorisation !'),
('scripter.warning.modtools.ticket.release', '%username% a tente de liberer un ticket sans autorisation !'),
('scripter.warning.packet.closedice', '%username% a tente de modifier un meuble qui n''est pas un de en utilisant le paquet de fermeture sur %id% %itemname%.'),
('scripter.warning.room.delete', '%username% a tente de supprimer la salle %roomname% appartenant a %roomowner%.'),
('scripter.warning.roomalert', '%username% a tente d''envoyer une alerte de salle sans autorisation !'),
('scripter.warning.roomsettings.category.nonexisting', '%username% a tente d''attribuer a sa salle une categorie inexistante !'),
('scripter.warning.roomsettings.category.permission', '%username% a tente d''attribuer a sa salle la categorie interdite %category%.'),
('scripter.warning.sticky.size', '%username% a tente de creer un post-it de %amount% caracteres alors que la limite est de %limit%.'),
('scripter.warning.userinfo', '%username% a demande les informations d''un joueur sans autorisation !')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- Derniers messages visibles herites du coeur Arcturus et de ses extensions.
INSERT INTO `emulator_texts` (`key`, `value`) VALUES
('alert.superwired.invalid', 'Configuration superwired invalide. N''utilisez pas <b>;</b> dans le champ produit !'),
('be.cmd_buildheight.invalid_height', 'Hauteur invalide ! Elle doit etre comprise entre 0 et 40.'),
('bots.butler.given', 'Voici votre %key%, %username%.'),
('bots.visitor.no_visits', 'Vous n''avez recu aucune visite pendant votre absence.'),
('bots.visitor.visits', 'Vous avez recu %count% visite(s) pendant votre absence. Pour connaitre les visiteurs, dites %positive%.'),
('bubblealerts.notif_friendonline.message', '%username% vient de se connecter ! Dites-lui bonjour !'),
('commands.description.cmd_allow_trading', 'Active ou desactive les echanges d''un joueur.'),
('commands.error.cmd_add_youtube_playlist.failed_playlist', 'Impossible de recuperer cette playlist YouTube.'),
('commands.error.cmd_add_youtube_playlist.no_base_item', 'Aucun meuble de base ne correspond a cet identifiant.'),
('commands.error.cmd_add_youtube_playlist.usage', 'Utilisation : identifiant_meuble identifiant_playlist_youtube'),
('commands.error.cmd_allow_trading.forgot_trade', 'Indiquez si vous souhaitez activer ou desactiver les echanges de %username%.'),
('commands.error.cmd_allow_trading.forgot_username', 'Indiquez le joueur dont vous souhaitez modifier les echanges.'),
('commands.error.cmd_allow_trading.incorrect_setting', 'Utilisez %enabled% pour activer les echanges ou %disabled% pour les desactiver.'),
('commands.error.cmd_allow_trading.user_not_found', 'Ce joueur n''existe pas.'),
('commands.error.cmd_badge.already_owns', '%user% possede deja le badge %badge%.'),
('commands.error.cmd_bundle.duplicate', 'Cette salle est deja en vente.'),
('commands.error.cmd_bundle.missing_params', 'Utilisation : :bundle <id_parent> <credits> <points> <type_points>'),
('commands.error.cmd_danceall.invalid_dance', 'Indiquez un numero de danse valide !'),
('commands.error.cmd_danceall.no_dance', 'Indiquez une danse comprise entre 0 et 4 !'),
('commands.error.cmd_danceall.outside_bounds', 'Le numero de danse doit etre compris entre 0 et 4.'),
('commands.error.cmd_duckets.invalid_amount', 'Indiquez un montant valide.'),
('commands.error.cmd_duckets.user_offline', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_filterword.error', 'Impossible d''ajouter ce mot au filtre. Il existe peut-etre deja.'),
('commands.error.cmd_filterword.missing_word', 'Indiquez le mot a filtrer et, si necessaire, son remplacement.'),
('commands.error.cmd_ha.forgot_message', 'Indiquez un message !'),
('commands.error.cmd_ip_ban.ban_self', 'Vous ne pouvez pas bannir votre propre adresse IP !'),
('commands.error.cmd_kick.unkickable', '%username% ne peut pas etre expulse !'),
('commands.error.cmd_machine_ban.ban_self', 'Vous ne pouvez pas bannir votre propre appareil !'),
('commands.error.cmd_masscredits.invalid_amount', 'Indiquez un montant valide.'),
('commands.error.cmd_massduckets.invalid_amount', 'Indiquez un montant valide.'),
('commands.error.cmd_masspoints.invalid_amount', 'Indiquez un montant valide.'),
('commands.error.cmd_masspoints.invalid_type', 'Type de points invalide. Choisissez parmi : %types%.'),
('commands.error.cmd_pet_info.pet_not_found', 'Indiquez le nom d''un animal !'),
('commands.error.cmd_points.invalid_amount', 'Indiquez un montant valide.'),
('commands.error.cmd_points.invalid_type', 'Type de points invalide. Choisissez parmi : %types%.'),
('commands.error.cmd_points.user_offline', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_promote_offer.not_found', 'Cette offre est introuvable. Utilisez :promoteoffer info pour voir les offres actives.'),
('commands.error.cmd_pull.invalid', 'Vous ne pouvez pas attirer %username% a cet endroit.'),
('commands.error.cmd_push.invalid', 'Vous ne pouvez pas pousser %username% a cet endroit.'),
('commands.error.cmd_say.forgot_username', 'Indiquez un pseudo !'),
('commands.error.cmd_say.hotel_view', '%user% ne se trouve dans aucune salle !'),
('commands.error.cmd_setmax.invalid_number', 'Nombre invalide. Indiquez une valeur comprise entre 0 et 9999.'),
('commands.error.cmd_setspeed.bounds', 'Indiquez une valeur comprise entre 0 et 100.'),
('commands.error.cmd_setspeed.invalid_amount', 'Indiquez un nombre valide.'),
('commands.error.cmd_set_poll.invalid_number', 'Indiquez un numero valide. Utilisez 0 pour retirer le sondage.'),
('commands.error.cmd_set_poll.missing_arg', 'Identifiant du sondage manquant. Utilisez 0 pour le retirer de la salle.'),
('commands.error.cmd_set_poll.not_found', 'Le sondage %id% est introuvable !'),
('commands.error.cmd_shout.forgot_username', 'Indiquez un pseudo !'),
('commands.error.cmd_shout.hotel_view', '%user% ne se trouve dans aucune salle !'),
('commands.error.cmd_softkick_error_self', 'Vous ne pouvez pas vous expulser vous-meme !'),
('commands.error.cmd_softkick_not_found', '%user% est introuvable.'),
('commands.error.cmd_staffalert.forgot_message', 'Indiquez le message a envoyer au staff.'),
('commands.error.cmd_staffonline.numbers_only', 'Indiquez uniquement des chiffres !'),
('commands.error.cmd_staffonline.positive_only', 'Indiquez uniquement des nombres positifs !'),
('commands.error.cmd_stalk.forgot_username', 'Indiquez le pseudo du joueur a rejoindre !'),
('commands.error.cmd_subscription.invalid_action', 'Action invalide. Utilisez add, +, remove ou -.'),
('commands.error.cmd_subscription.invalid_params', 'Format de commande invalide.'),
('commands.error.cmd_subscription.invalid_params_time', 'Duree invalide. Utilisez : x minutes/days/weeks/months.'),
('commands.error.cmd_subscription.success_add_time', '%time% seconde(s) ont ete ajoutees a l''abonnement %subscription% de %user%.'),
('commands.error.cmd_subscription.success_remove_sub', 'L''abonnement %subscription% de %user% a ete retire.'),
('commands.error.cmd_subscription.success_remove_time', '%time% seconde(s) ont ete retirees de l''abonnement %subscription% de %user%.'),
('commands.error.cmd_subscription.type_not_found', '%subscription% n''est pas un type d''abonnement valide.'),
('commands.error.cmd_subscription.user_not_found', '%user% est introuvable.'),
('commands.error.cmd_subscription.user_not_have', '%user% ne possede pas l''abonnement %subscription%.'),
('commands.error.cmd_summon.forgot_username', 'Indiquez le pseudo du joueur a teleporter !'),
('commands.error.cmd_summon.not_found', 'Ce joueur n''est pas en ligne !'),
('commands.error.cmd_super_ban.ban_self', 'Vous ne pouvez pas vous bannir vous-meme !'),
('commands.error.cmd_take_badge.forgot_username', 'Indiquez un pseudo !'),
('commands.error.cmd_take_badge.no_badge', '%username% ne possede pas le badge %badge% !'),
('commands.errors.cmd_give_rank.not_found', 'Le grade %id% n''existe pas et ne peut pas etre attribue a %username% !'),
('commands.errors.cmd_hidewired.permission', 'Vous n''avez pas la permission de masquer les wireds dans cette salle !'),
('commands.generic.cmd_stalk.same_room', '%user% se trouve deja dans cette salle !'),
('commands.generic.cmd_summon.same_room', '%user% se trouve deja dans cette salle !'),
('commands.generic.cmd_transform.title', 'Animaux disponibles :'),
('commands.succes.cmd_add_youtube_playlist', 'La playlist a ete ajoutee !'),
('commands.succes.cmd_allow_trading.disabled', 'Les echanges de %username% ont ete desactives !'),
('commands.succes.cmd_allow_trading.enabled', 'Les echanges de %username% ont ete actives !'),
('commands.succes.cmd_bundle', 'Le lot de salle a ete cree sur la page %id%.'),
('commands.succes.cmd_diagonal.disabled', 'Vous ne pouvez plus marcher en diagonale !'),
('commands.succes.cmd_duckets.send', '%amount% duckets ont ete envoyes a %user% !'),
('commands.succes.cmd_empty_bots.verify', 'Cette action supprimera tous les bots de votre inventaire. Saisissez :emptybots %generic.yes% pour confirmer !'),
('commands.succes.cmd_empty_pets.verify', 'Cette action supprimera tous les animaux de votre inventaire. Saisissez :emptypets %generic.yes% pour confirmer !'),
('commands.succes.cmd_filterword.added', 'Le mot %word% a ete ajoute au filtre avec le remplacement %replacement% !'),
('commands.succes.cmd_freeze_bots.unfrozen', 'Les bots peuvent maintenant se deplacer dans votre salle.'),
('commands.succes.cmd_ip_ban', '%count% compte(s) ont ete bannis par adresse IP !'),
('commands.succes.cmd_machine_ban', '%count% compte(s) ont ete bannis par appareil !'),
('commands.succes.cmd_mimic.copied', 'Vous avez copie l''apparence de %user% !'),
('commands.succes.cmd_mute_bots.ignored', 'Vous ignorez maintenant les bots.'),
('commands.succes.cmd_mute_bots.unignored', 'Vous n''ignorez plus les bots.'),
('commands.succes.cmd_mute_pets.ignored', 'Vous ignorez maintenant les animaux.'),
('commands.succes.cmd_mute_pets.unignored', 'Vous n''ignorez plus les animaux.'),
('commands.succes.cmd_points.send', '%amount% %type% ont ete envoyes a %user% !'),
('commands.succes.cmd_promote_offer', 'L''offre mise en avant est maintenant %id% : %title%.'),
('commands.succes.cmd_say', '%user% a dit : %message%'),
('commands.succes.cmd_set_poll', 'Le sondage de la salle a ete mis a jour !'),
('commands.succes.cmd_shout', '%user% a crie : %message%'),
('commands.succes.cmd_summon.summoned', '%user% a ete teleporte !'),
('commands.succes.cmd_super_ban', '%count% compte(s) ont ete bannis definitivement !'),
('commands.succes.cmd_update_achievements.updated', 'Les succes ont ete recharges !'),
('commands.succes.cmd_update_guildparts', 'Les elements et le generateur de badges de groupe ont ete recharges !'),
('commands.succes.cmd_update_pet_data', 'Les donnees des animaux ont ete actualisees !'),
('commands.succes.cmd_update_polls', 'Les sondages des salles ont ete recharges !'),
('commands.succes.cmd_update_youtube_playlists', 'Les playlists YouTube ont ete actualisees !'),
('commands.success.cmd_setmax', 'Le nombre maximal de joueurs dans cette salle est maintenant de %value%.'),
('commands.success.cmd_update_calendar', 'Le calendrier a ete mis a jour !'),
('commands.success.cmd_update_chat_bubbles', 'Les bulles de discussion ont ete mises a jour.'),
('error.catalog.buy.limited.daily.item', 'Vous avez atteint la limite quotidienne de %limit% exemplaire(s) pour %itemname%. Revenez demain.'),
('error.catalog.buy.limited.daily.total', 'Vous avez atteint la limite quotidienne de %limit% meubles rares. Revenez demain.'),
('error.recycler.box.empty', 'Cette boite ne contient aucune recompense. Elle va etre retiree.'),
('generic.error.ignore_higher_rank', 'Vous ne pouvez pas ignorer ce joueur.'),
('generic.shutdown', 'Le serveur va s''arreter. Les prochaines modifications risquent de ne pas etre sauvegardees !'),
('generic.tile.not.exists', 'Cette case n''existe pas !'),
('hotel.error.roomads.nopermission', 'Vous n''avez pas la permission de modifier les publicites de cette salle !'),
('hotel.wired.giveachievement.invalid.achievement', 'Le succes %achievement% n''existe pas !'),
('hotel.wired.giveachievement.invalid.points', 'Cette valeur n''est pas un nombre !'),
('stalk.failed.same.room', '%user% se trouve aussi dans cette salle !'),
('warning.auto.report', '%user% a declenche le filtre avec le mot : %word%')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

INSERT INTO emulator_texts (`key`, `value`) VALUES
('macro.duplicate', 'Vous possédez déjà une macro portant ce nom.'),
('macro.size', 'Le nom de votre macro doit contenir entre 4 et 15 caractères.'),
('macro.limit', 'Vous avez trop de macros. Supprimez-en avant d''en créer une nouvelle.'),
('commands.error.cmd_alert.forgot_message', 'Indiquez un message.'),
('commands.error.cmd_alert.forgot_username', 'Indiquez un pseudo.'),
('commands.error.cmd_alert.user_offline', 'Le joueur %user% n''est pas en ligne.'),
('commands.error.cmd_badge.already_owned', '%user% possède déjà le badge %badge%.'),
('commands.error.cmd_badge.forgot_badge', 'Indiquez le badge à donner à %user%.'),
('commands.error.cmd_badge.forgot_username', 'Indiquez le joueur qui recevra le badge.'),
('commands.error.cmd_ban.ban_self', 'Vous ne pouvez pas vous bannir vous-même.'),
('commands.error.cmd_ban.forgot_time', 'Indiquez une durée en secondes.'),
('commands.error.cmd_ban.forgot_user', 'Indiquez un pseudo.'),
('commands.error.cmd_ban.invalid_time', 'Indiquez une durée valide.'),
('commands.error.cmd_ban.target_rank_higher', 'Ce joueur possède un grade supérieur au vôtre.'),
('commands.error.cmd_ban.time_to_short', 'La durée du bannissement doit être supérieure à 600 secondes.'),
('commands.error.cmd_ban.user_offline', 'Ce joueur est introuvable.'),
('commands.error.cmd_chatcolor.banned', 'Cette couleur de chat n''est pas autorisée.'),
('commands.error.cmd_chatcolor.no_number', 'Indiquez l''ID d''une couleur.'),
('commands.error.cmd_chatcolor.numbers', 'Utilisez uniquement un nombre positif.'),
('commands.error.cmd_control.not_found', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_control.not_self', 'Vous ne pouvez pas prendre le contrôle de votre propre personnage.'),
('commands.error.cmd_credits.invalid_amount', 'Indiquez un montant valide.'),
('commands.error.cmd_credits.user_not_found', 'Impossible d''envoyer %amount% crédits : %user% est introuvable.'),
('commands.error.cmd_credits.user_offline', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_disconnect.disconnect_self', 'Vous ne pouvez pas vous déconnecter vous-même.'),
('commands.error.cmd_disconnect.forgot_username', 'Indiquez un pseudo.'),
('commands.error.cmd_disconnect.higher_rank', 'Ce joueur possède un grade supérieur au vôtre.'),
('commands.error.cmd_disconnect.user_offline', 'Ce joueur est introuvable.'),
('commands.error.cmd_enable.not_allowed', 'Vous n''avez pas la permission d''utiliser cet effet.'),
('commands.error.cmd_freeze.not_found', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_gift.not_a_number', 'Indiquez un nombre positif.'),
('commands.error.cmd_gift.not_found', 'L''objet %itemid% est introuvable.'),
('commands.error.cmd_gift.user_not_found', 'Le joueur %username% n''est pas en ligne.'),
('commands.error.cmd_give_rank.higher', 'Vous ne pouvez pas attribuer à %username% un grade supérieur au vôtre.'),
('commands.error.cmd_give_rank.higher.other', '%username% possède un grade supérieur au vôtre.'),
('commands.error.cmd_give_rank.missing_rank', 'Grade manquant. Syntaxe : '),
('commands.error.cmd_give_rank.missing_username', 'Pseudo manquant. Syntaxe : '),
('commands.error.cmd_give_rank.not_found', 'Le grade %id% est introuvable.'),
('commands.error.cmd_give_rank.user_offline', '%username% n''est pas en ligne.'),
('commands.error.cmd_mimic.blocked', 'Vous ne pouvez pas copier l''apparence de %user%.'),
('commands.error.cmd_mimic.forbidden_clothing', 'Ce joueur porte des vêtements que vous ne possédez pas.'),
('commands.error.cmd_mimic.not_found', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_mimic.not_self', 'Vous ne pouvez pas copier votre propre apparence.'),
('commands.error.cmd_mute.not_found', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_mute.not_specified', 'Indiquez le joueur à rendre muet.'),
('commands.error.cmd_mute.self', 'Vous ne pouvez pas vous rendre muet vous-même.'),
('commands.error.cmd_mute.time', 'La durée doit être d''au moins une seconde.'),
('commands.error.cmd_pull.cant_reach', 'Le joueur %user% est trop loin.'),
('commands.error.cmd_pull.not_found', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_pull.pull_self', 'Vous ne pouvez pas vous attirer vous-même.'),
('commands.error.cmd_push.cant_reach', 'Le joueur %user% est trop loin.'),
('commands.error.cmd_push.not_found', 'Le joueur %user% est introuvable.'),
('commands.error.cmd_push.push_self', 'Vous ne pouvez pas vous pousser vous-même.'),
('commands.error.cmd_roomalert.empty', 'Indiquez un message.'),
('commands.error.cmd_roomeffect.no_effect', 'Indiquez un effet.'),
('commands.error.cmd_roomeffect.numbers_only', 'Utilisez uniquement des nombres.'),
('commands.error.cmd_roomitem.no_item', 'Indiquez l''ID d''un objet.'),
('commands.error.cmd_say.user_not_found', 'Ce joueur est introuvable.'),
('commands.error.cmd_shout.user_not_found', 'Ce joueur est introuvable.'),
('commands.error.cmd_stalk.not_found', '%user% n''est pas en ligne.'),
('commands.error.cmd_stalk.not_room', '%user% ne se trouve dans aucune salle.'),
('commands.error.cmd_unban.not_found', 'Aucun bannissement trouvé pour %user%.'),
('commands.error.cmd_unban.not_specified', 'Indiquez un pseudo.'),
('commands.error.cmd_unban.success', 'Le bannissement de %user% a été levé.'),
('commands.error.cmd_unmute.not_found', '%user% n''est pas en ligne.'),
('commands.error.cmd_unmute.not_muted', '%user% n''est pas muet.'),
('commands.error.cmd_unmute.not_specified', 'Indiquez le joueur à réautoriser à parler.'),
('commands.error.cmd_userinfo.forgot_username', 'Indiquez un pseudo.'),
('commands.error.cmd_userinfo.not_found', 'Le joueur %user% est introuvable.'),
('commands.generic.cmd_badge.received', 'Vous avez reçu un badge !'),
('commands.generic.cmd_coords.title', '<b>Votre position actuelle</b>'),
('commands.generic.cmd_credits.received', 'Vous avez reçu %amount% crédits !'),
('commands.generic.cmd_duckets.received', 'Vous avez reçu %amount% duckets !'),
('commands.generic.cmd_give_rank.new_rank', 'Votre grade est maintenant %id%.'),
('commands.generic.cmd_pet_info.stats', '<b>Statistiques de l''animal :</b>'),
('commands.generic.cmd_pet_info.title', '<b>Informations sur l''animal</b>'),
('commands.generic.cmd_points.received', 'Vous avez reçu %amount% %type% !'),
('commands.generic.cmd_staffalert.title', '<b>Alerte staff :</b>'),
('commands.generic.cmd_staffonline.staffs', '<b>Staffs en ligne :</b>'),
('commands.generic.cmd_summon.been_summoned', 'Vous avez été téléporté par %user%.'),
('commands.generic.cmd_summon.summoning', 'Téléportation de %user%...'),
('commands.succes.cmd_alert.message_send', 'L''alerte a été envoyée à %user%.'),
('commands.succes.cmd_badge.given', 'Le badge %badge% a été donné à %user%.'),
('commands.succes.cmd_ban.ban_issued', '%user% a été banni pendant %time% seconde(s). Motif : %reason%'),
('commands.succes.cmd_chatcolor.reset', 'La couleur du chat a été réinitialisée.'),
('commands.succes.cmd_chatcolor.set', 'Votre nouvelle couleur de chat est : %chat%.'),
('commands.succes.cmd_control.controlling', 'Vous contrôlez maintenant %user%.'),
('commands.succes.cmd_control.stopped', 'Vous ne contrôlez plus %user%.'),
('commands.succes.cmd_credits.send', '%amount% crédits ont été envoyés à %user%.'),
('commands.succes.cmd_disconnect.disconnected', '%user% a été déconnecté.'),
('commands.succes.cmd_empty.cleared', 'Votre inventaire a été vidé.'),
('commands.succes.cmd_empty.verify', 'Cette action supprimera tous les objets de votre inventaire. Tapez :empty %generic.yes% pour confirmer.'),
('commands.succes.cmd_freeze.frozen', 'Vous avez été immobilisé.'),
('commands.succes.cmd_freeze.unfrozen', 'Vous pouvez de nouveau bouger.'),
('commands.succes.cmd_freeze.user_frozen', '%user% a été immobilisé.'),
('commands.succes.cmd_freeze.user_unfrozen', '%user% peut de nouveau bouger.'),
('commands.succes.cmd_gift', 'L''objet %itemname% a été envoyé à %username%.'),
('commands.succes.cmd_give_rank.updated', '%username% possède maintenant le grade %id%.'),
('commands.succes.cmd_invisible.updated', 'Vous êtes maintenant invisible. Rechargez la salle pour annuler.'),
('commands.succes.cmd_invisible.updated.back', 'Vous êtes de nouveau visible.'),
('commands.succes.cmd_mute.muted', '%user% est maintenant muet.'),
('commands.succes.cmd_mute.unmuted', '%user% peut de nouveau parler.'),
('commands.succes.cmd_pull.pull', '* Attire %user% vers soi *'),
('commands.succes.cmd_push.push', '* Repousse %user% *'),
('commands.succes.cmd_roommute.muted', 'Le chat de la salle a été désactivé.'),
('commands.succes.cmd_roommute.unmuted', 'Le chat de la salle a été réactivé.'),
('commands.succes.cmd_take_badge', 'Le badge a été retiré.'),
('commands.succes.cmd_teleport.disabled', 'La téléportation est désactivée.'),
('commands.succes.cmd_teleport.enabled', 'La téléportation est activée.'),
('commands.succes.cmd_unmute', '%user% peut de nouveau parler.'),
('commands.succes.cmd_update_catalog', 'Le catalogue a été actualisé.'),
('commands.succes.cmd_update_config', 'La configuration a été rechargée.'),
('commands.succes.cmd_update_items', 'Les objets ont été actualisés.'),
('commands.succes.cmd_update_navigator', 'Le navigateur a été rechargé.'),
('commands.succes.cmd_update_permissions', 'Les permissions ont été actualisées.'),
('commands.succes.cmd_update_plugins', '%count% plugin(s) ont été rechargés.'),
('commands.succes.cmd_update_texts', 'Les textes ont été actualisés.'),
('commands.error.cmd_update_texts.failed', 'Impossible d''actualiser les textes.')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

INSERT INTO emulator_texts (`key`, `value`) VALUES
('commands.generic.cmd_commands.text', 'Vos commandes'),
('commands.description.cmd_911', ':aide - Appeler la police.'),
('commands.description.cmd_accept_offer', ':accepteroffre <code> - Accepter une offre.'),
('commands.description.cmd_apply', ':utiliser <objet> - Utiliser un objet de votre inventaire.'),
('commands.description.cmd_balance', ':solde - Consulter votre solde bancaire.'),
('commands.description.cmd_bucks', ':argent <pseudo> <montant> - Donner des Bucks.'),
('commands.description.cmd_charge', ':inculper <pseudo> <délit> - Inculper un joueur.'),
('commands.description.cmd_clear_offer', ':effaceroffres - Annuler vos offres en cours.'),
('commands.description.cmd_combat_stats', ':combat [pseudo] - Consulter les statistiques de combat.'),
('commands.description.cmd_decline_offer', ':refuseroffre <code> - Refuser une offre.'),
('commands.description.cmd_demote', ':retrograder <pseudo> - Rétrograder un employé.'),
('commands.description.cmd_deposit', ':depot <montant> - Déposer des Bucks sur votre compte.'),
('commands.description.cmd_equip', ':equiper <objet> - Équiper une arme ou une protection.'),
('commands.description.cmd_fire', ':licencier <pseudo> - Licencier un employé.'),
('commands.description.cmd_give', ':virement <pseudo> <montant> - Effectuer un virement bancaire.'),
('commands.description.cmd_hire', ':recruter <pseudo> - Recruter un employé.'),
('commands.description.cmd_hit', ':frapper <pseudo> - Frapper un joueur.'),
('commands.description.cmd_hotrooms', ':salles - Afficher les salles les plus actives.'),
('commands.description.cmd_offer_rpitem', ':proposer <pseudo> <objet> - Proposer un objet lié à votre métier.'),
('commands.description.cmd_openaccount', ':ouvrircompte - Ouvrir un compte bancaire.'),
('commands.description.cmd_passive', ':passif - Activer ou désactiver le mode passif.'),
('commands.description.cmd_promote', ':promouvoir <pseudo> - Promouvoir un employé.'),
('commands.description.cmd_quit_job', ':demissionner - Quitter votre métier.'),
('commands.description.cmd_rob', ':braquer <pseudo> <montant> - Braquer un joueur.'),
('commands.description.cmd_sell_rpitem', ':vendre <pseudo> <objet> - Vendre un objet de votre inventaire.'),
('commands.description.cmd_send_home', ':renvoyer <pseudo> [minutes] - Renvoyer temporairement un employé.'),
('commands.description.cmd_shoot', ':tirer <pseudo> - Tirer sur un joueur.'),
('commands.description.cmd_spit', ':cracher <pseudo> - Cracher sur un joueur.'),
('commands.description.cmd_target_lock', ':verrouillercible - Verrouiller la cible sélectionnée.'),
('commands.description.cmd_taxi', ':taxi <ID de salle> - Appeler un taxi.'),
('commands.description.cmd_transactions', ':transactions - Consulter vos dernières opérations bancaires.'),
('commands.description.cmd_unequip', ':desequiper - Ranger votre équipement.'),
('commands.description.cmd_wanted_list', ':recherches - Afficher les personnes recherchées.'),
('commands.description.cmd_withdraw', ':retirer <montant> - Retirer des Bucks de votre compte.'),
('commands.cmd_sell_item.error.params', 'Indiquez le nom de l''objet et la quantité à vendre. Exemple : :vendreobjet carotte 10'),
('commands.cmd_sell_item.error.params.amount', 'Indiquez une quantité valide.'),
('commands.cmd_sell_item.error.params.item', 'L''objet %item% est introuvable.'),
('commands.cmd_sell_item.error.wrong_room', 'Vous ne pouvez pas vendre cet objet dans cette salle.'),
('commands.cmd_sell_item.successfully', 'Vous avez vendu %amount% exemplaire(s) de %item%.'),
('commands.cmd_update_farm.error', 'Impossible de mettre à jour le système agricole.'),
('commands.cmd_update_farm.successfully', 'Le système agricole a été mis à jour.'),
('commands.cmd_update_item_marketplace.success', 'Le marché des objets a été mis à jour.'),
('generic.cannot_do_that', 'Vous ne pouvez pas faire cela.'),
('generic.habbo.notfound', 'Joueur introuvable'),
('generic.user.not_found', '%user% est introuvable.'),
('generic.reason.specified', 'Motif indiqué'),
('generic.credits', 'crédits'),
('generic.gift.received', '%username% vous a offert un cadeau !'),
('generic.gift.received.anonymous', 'Vous avez reçu un cadeau !'),
('generic.furniture.bought', 'Vous avez acheté %amount%%is_limited%%itemname%%limited_display% !'),
('generic.furniture.sold', 'Votre objet %item% a été vendu. Cliquez ici pour récupérer vos crédits !'),
('inventory.full', 'Votre inventaire est plein. Placez des meubles avant d''en acheter davantage !'),
('loggedin.elsewhere', 'Vous avez été déconnecté, car votre compte s''est connecté ailleurs.'),
('invisible.prevent.chat.error', 'Vous ne pouvez pas parler lorsque vous êtes invisible.'),
('camera.disabled', 'La caméra est désactivée.'),
('camera.error.creation', 'Impossible de créer votre photo.'),
('camera.permission', 'Vous n''avez pas la permission d''utiliser la caméra.'),
('camera.wait', 'Attendez %seconds% seconde(s) avant de prendre une autre photo.'),
('floorplan.permission', 'Vous n''avez pas la permission d''utiliser l''éditeur de sol.'),
('error.bots.max.inventory', 'Vous avez atteint la limite de %amount% bots dans votre inventaire.'),
('error.pets.max.inventory', 'Vous avez atteint la limite de %amount% animaux dans votre inventaire.'),
('error.catalog.buy.not_yet', 'Cet achat n''est pas encore disponible.'),
('farm.warn.cooldown', 'Attendez %time% seconde(s) avant de recommencer.'),
('farm.warn.harvested', 'Vous avez récolté %item% !'),
('farm.warn.missing_effect', 'Vous devez porter l''effet %effect% pour effectuer cette action.'),
('farm.warn.missing_item', 'Il vous faut l''objet %item% x%amount%.'),
('roleplay.error.change_clothing.not_allowed', 'Vous ne pouvez pas vous changer ici. Rendez-vous dans un magasin de vêtements !'),
('bubblealerts.notif_mention.message', '%username% vous a mentionné. Cliquez pour le rejoindre dans %room_name% !'),
('hotel.alert.message.welcome', 'Bienvenue sur ParadiseRP, %user% !'),
('rcon.alert.user.change_username', 'Vous pouvez changer de pseudo. Cliquez sur votre personnage pour le modifier.'),
('subscriptions.hc.payday.message', 'Votre paie HC est arrivée ! Vous avez reçu %amount% crédits.'),
('supporttools.not_ticket_owner', 'Vous n''êtes pas le modérateur chargé de ce ticket.'),
('support.ticket.picked.failed', 'Impossible de prendre ce ticket : il est déjà traité ou n''existe plus.'),
('ban.info.user_id', 'ID du joueur : '),
('ban.info.type', 'Type de sanction : '),
('ban.info.reason', 'Motif : '),
('ban.info.staff_id', 'ID du staff : '),
('ban.info.date_issued', 'Date : '),
('ban.info.date_expire', 'Date d''expiration : '),
('command.cmd_userinfo.user_name', 'Pseudo'),
('command.cmd_userinfo.online', 'En ligne'),
('command.cmd_userinfo.banned', 'Banni'),
('command.cmd_userinfo.credits', 'Crédits'),
('command.cmd_userinfo.room', 'Salle'),
('command.cmd_userinfo.total_bans', 'Nombre de sanctions'),
('command.cmd_userinfo.ban_info', 'Dernière sanction'),
('command.cmd_userinfo.userinfo', 'Informations du joueur'),
('command.cmd_userinfo.pet_respect_left', 'Respects animaux restants'),
('nux.step.1', 'Ce bouton vous ramène à l''accueil de l''hôtel.'),
('nux.step.2', 'Ce bouton ouvre le navigateur pour visiter d''autres salles.'),
('nux.step.3', 'Saisissez votre message ici pour parler.'),
('nux.step.4', 'L''historique du chat permet de relire vos conversations.'),
('nux.step.5', 'Utilisez la garde-robe pour changer votre apparence.'),
('nux.step.6', 'Achetez des meubles dans le catalogue pour décorer votre appartement.'),
('nux.step.7', 'Les meubles peuvent être achetés avec différentes monnaies.'),
('nux.step.10', 'Vos amis sont affichés ici.'),
('nux.step.11', 'Partez maintenant à la découverte de ParadiseRP !')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

INSERT INTO `emulator_texts` (`key`, `value`) VALUES
('hotel.wired.kickexception.owner', 'Exception du wired d''expulsion : propriétaire de la salle'),
('pirate_parrot.message.1', 'Fais ce que tu veux, un pirate est libre !'),
('pirate_parrot.message.4', 'Espèce de sale petit pirate !')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);
