-- Traduction des libelles visibles du catalogue en jeu.
-- Les identifiants, relations et noms techniques restent inchanges.
SET NAMES utf8mb4;

UPDATE catalog_pages SET caption = CASE caption
    WHEN 'Club Gifts' THEN 'Cadeaux du Club'
    WHEN 'Diner' THEN 'Restaurant'
    WHEN 'Extras' THEN 'Extras'
    WHEN 'Campaigns' THEN 'Campagnes'
    WHEN 'Furni By Line' THEN 'Mobilier par collection'
    WHEN 'Greek' THEN 'Grec'
    WHEN 'Game Shop' THEN 'Boutique de jeux'
    WHEN 'Room Bundles' THEN 'Packs d''appartements'
    WHEN 'Pet Equipment' THEN 'Accessoires pour animaux'
    WHEN 'Redeemable Cases' THEN 'Caisses échangeables'
    WHEN 'Seasonal Gifts' THEN 'Cadeaux saisonniers'
    WHEN 'Limited Edition Rares' THEN 'Rares en édition limitée'
    WHEN 'Purchase History' THEN 'Historique des achats'
    WHEN 'Colourable Rares' THEN 'Rares personnalisables'
    WHEN 'V7 Rares' THEN 'Rares V7'
    WHEN 'Collectibles' THEN 'Objets de collection'
    WHEN 'V11 Rares' THEN 'Rares V11'
    WHEN 'Seasonal Furni Lines' THEN 'Collections saisonnières'
    WHEN 'Christmas' THEN 'Noël'
    WHEN 'Easter' THEN 'Pâques'
    WHEN 'Halloween' THEN 'Halloween'
    WHEN 'Valentines Day' THEN 'Saint-Valentin'
    WHEN 'New Years' THEN 'Nouvel An'
    WHEN 'Public Room Furni' THEN 'Mobilier des lieux publics'
    WHEN 'Summer' THEN 'Été'
    WHEN 'New Year Accessories' THEN 'Accessoires du Nouvel An'
    WHEN 'Ad Sales' THEN 'Vente de publicités'
    WHEN 'Habbo Stories' THEN 'Histoires ParadiseRP'
    WHEN 'Rare Groups' THEN 'Groupes de rares'
    WHEN 'Classic Furni Lines' THEN 'Collections classiques'
    WHEN 'Bonus Prizes' THEN 'Récompenses bonus'
    WHEN 'Outdoor Furni' THEN 'Mobilier extérieur'
    WHEN 'Room Building' THEN 'Construction d''appartement'
    WHEN 'Indoor Furni' THEN 'Mobilier intérieur'
    WHEN 'Clothing' THEN 'Vêtements'
    WHEN 'Crackable Prizes' THEN 'Récompenses à ouvrir'
    WHEN 'Seasonal Crackables' THEN 'Objets saisonniers à ouvrir'
    WHEN 'Crafting' THEN 'Fabrication'
    WHEN 'Previous Campaigns' THEN 'Anciennes campagnes'
    WHEN 'Pets' THEN 'Animaux'
    WHEN 'Rares by Furni Line' THEN 'Rares par collection'
    WHEN 'Executive' THEN 'Direction'
    WHEN 'Ingredients' THEN 'Ingrédients'
    WHEN 'Pirates' THEN 'Pirates'
    WHEN 'Rares by Year' THEN 'Rares par année'
    WHEN 'Bonus Rares' THEN 'Rares bonus'
    ELSE caption
END
WHERE enabled = 1;
