<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');
require_once __DIR__ . '/../app/Controller/Config.class.php';
require_once __DIR__ . '/../app/Controller/DBManager.class.php';
require_once __DIR__ . '/../app/Modal/SessionMG.class.php';
function phone_json(array $data,int $status=200):void{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function phone_stmt(mysqli $db,string $sql,string $types='',array $params=[]):mysqli_stmt{$stmt=$db->prepare($sql);if(!$stmt)throw new RuntimeException('Service temporairement indisponible.');if($types!=='')$stmt->bind_param($types,...$params);if(!$stmt->execute())throw new RuntimeException('Opération impossible.');return $stmt;}
function phone_body():array{$data=json_decode((string)file_get_contents('php://input'),true);return is_array($data)?$data:[];}
function phone_text(mixed $value,int $max,bool $required=false):string{$value=trim((string)$value);if(($required&&$value==='')||mb_strlen($value)>$max)throw new InvalidArgumentException('Le contenu saisi est invalide.');return $value;}
function phone_photo_available(string $url):bool{
  if($url==='')return false;
  $path=(string)(parse_url($url,PHP_URL_PATH)??'');
  if(str_starts_with($path,'/nitro/camera-photos/'))return is_file(__DIR__.substr($path,strlen('/nitro')));
  return true;
}
function phone_feed(mysqli $db,int $userId,string $csrf):void{
  $posts=[];
  $sql='SELECT p.id,p.user_id,p.body,p.image_url,p.created_at,u.username,u.look,(SELECT COUNT(*) FROM phone_gram_likes l WHERE l.post_id=p.id) likes,EXISTS(SELECT 1 FROM phone_gram_likes l2 WHERE l2.post_id=p.id AND l2.user_id=?) liked,EXISTS(SELECT 1 FROM phone_gram_follows f WHERE f.follower_id=? AND f.following_id=p.user_id) following,(SELECT COUNT(*) FROM phone_gram_follows f2 WHERE f2.following_id=p.user_id) followers,(SELECT COUNT(*) FROM phone_gram_follows f3 WHERE f3.follower_id=p.user_id) following_count FROM phone_gram_posts p JOIN users u ON u.id=p.user_id ORDER BY p.created_at DESC,p.id DESC LIMIT 100';
  $result=phone_stmt($db,$sql,'ii',[$userId,$userId])->get_result();
  while($row=$result->fetch_assoc()){
    $comments=[];$cr=phone_stmt($db,'SELECT c.id,c.user_id,c.body,c.created_at,u.username,u.look FROM phone_gram_comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=? ORDER BY c.id ASC LIMIT 100','i',[(int)$row['id']])->get_result();
    while($c=$cr->fetch_assoc())$comments[]=['id'=>(int)$c['id'],'userId'=>(int)$c['user_id'],'username'=>$c['username'],'look'=>$c['look'],'body'=>$c['body'],'createdAt'=>(int)$c['created_at'],'canDelete'=>(int)$c['user_id']===$userId];
    $posts[]=['id'=>(int)$row['id'],'userId'=>(int)$row['user_id'],'username'=>$row['username'],'look'=>$row['look'],'body'=>$row['body'],'imageUrl'=>$row['image_url'],'createdAt'=>(int)$row['created_at'],'likes'=>(int)$row['likes'],'liked'=>(bool)$row['liked'],'following'=>(bool)$row['following'],'followers'=>(int)$row['followers'],'followingCount'=>(int)$row['following_count'],'canDelete'=>(int)$row['user_id']===$userId,'comments'=>$comments];
  }
  $gallery=[];$gr=phone_stmt($db,'SELECT id,room_id,timestamp,url FROM camera_photos WHERE user_id=? ORDER BY timestamp DESC,id DESC LIMIT 250','i',[$userId])->get_result();while($g=$gr->fetch_assoc())if(phone_photo_available((string)$g['url']))$gallery[]=['id'=>(int)$g['id'],'roomId'=>(int)$g['room_id'],'timestamp'=>(int)$g['timestamp'],'url'=>$g['url']];
  $suggestions=[];
  $sr=phone_stmt($db,'SELECT u.id,u.username,u.look,(SELECT COUNT(*) FROM phone_gram_posts p WHERE p.user_id=u.id) posts,(SELECT COUNT(*) FROM phone_gram_follows f WHERE f.following_id=u.id) followers,(SELECT COUNT(*) FROM phone_gram_follows f2 WHERE f2.follower_id=u.id) following_count,EXISTS(SELECT 1 FROM phone_gram_follows f3 WHERE f3.follower_id=? AND f3.following_id=u.id) following FROM users u WHERE u.id<>? ORDER BY posts DESC,followers DESC,u.username ASC LIMIT 60','ii',[$userId,$userId])->get_result();
  while($s=$sr->fetch_assoc())$suggestions[]=['id'=>(int)$s['id'],'username'=>$s['username'],'look'=>$s['look'],'posts'=>(int)$s['posts'],'followers'=>(int)$s['followers'],'followingCount'=>(int)$s['following_count'],'following'=>(bool)$s['following']];
  $me=phone_stmt($db,'SELECT u.id,u.username,u.look,(SELECT COUNT(*) FROM phone_gram_posts p WHERE p.user_id=u.id) posts,(SELECT COUNT(*) FROM phone_gram_follows f WHERE f.following_id=u.id) followers,(SELECT COUNT(*) FROM phone_gram_follows f2 WHERE f2.follower_id=u.id) following_count FROM users u WHERE u.id=? LIMIT 1','i',[$userId])->get_result()->fetch_assoc();
  $activity=[];$ar=phone_stmt($db,'SELECT n.actor_id,n.type,n.post_id,n.created_at,u.username,u.look FROM phone_gram_notifications n JOIN users u ON u.id=n.actor_id WHERE n.user_id=? ORDER BY n.created_at DESC,n.id DESC LIMIT 50','i',[$userId])->get_result();while($a=$ar->fetch_assoc())$activity[]=['userId'=>(int)$a['actor_id'],'type'=>$a['type'],'postId'=>$a['post_id']!==null?(int)$a['post_id']:null,'createdAt'=>(int)$a['created_at'],'username'=>$a['username'],'look'=>$a['look']];
  phone_json(['ok'=>true,'csrf'=>$csrf,'posts'=>$posts,'gallery'=>$gallery,'activity'=>$activity,'suggestions'=>$suggestions,'me'=>['id'=>(int)$me['id'],'username'=>$me['username'],'look'=>$me['look'],'posts'=>(int)$me['posts'],'followers'=>(int)$me['followers'],'followingCount'=>(int)$me['following_count']]]);
}
try{
  $session=new SessionMG();if(!$session->Exist(Config::$SessionName))phone_json(['ok'=>false,'error'=>'Session expirée.'],401);
  $db=(new DBManager())->Con();$username=trim((string)$session->Read(Config::$SessionName));$user=phone_stmt($db,'SELECT id,username FROM users WHERE username=? LIMIT 1','s',[$username])->get_result()->fetch_assoc();if(!$user)phone_json(['ok'=>false,'error'=>'Compte introuvable.'],401);$userId=(int)$user['id'];
  if(!isset($_SESSION['paradise_phone_csrf']))$_SESSION['paradise_phone_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['paradise_phone_csrf'];$action=strtolower(trim((string)($_GET['action']??'')));
  if($action==='gallery'&&$_SERVER['REQUEST_METHOD']==='GET'){$photos=[];$r=phone_stmt($db,'SELECT id,room_id,timestamp,url FROM camera_photos WHERE user_id=? ORDER BY timestamp DESC,id DESC LIMIT 250','i',[$userId])->get_result();while($row=$r->fetch_assoc())if(phone_photo_available((string)$row['url']))$photos[]=['id'=>(int)$row['id'],'roomId'=>(int)$row['room_id'],'timestamp'=>(int)$row['timestamp'],'url'=>$row['url']];phone_json(['ok'=>true,'photos'=>$photos]);}
  if($action!=='feed')phone_json(['ok'=>false,'error'=>'Application inconnue.'],404);if($_SERVER['REQUEST_METHOD']==='GET')phone_feed($db,$userId,$csrf);if($_SERVER['REQUEST_METHOD']!=='POST')phone_json(['ok'=>false,'error'=>'Méthode refusée.'],405);
  $data=phone_body();if(!hash_equals($csrf,(string)($data['csrf']??'')))phone_json(['ok'=>false,'error'=>'Session de sécurité expirée.'],403);$op=strtolower(trim((string)($data['action']??'')));$postId=max(0,(int)($data['postId']??0));$now=time();
  if($op==='create'){$body=phone_text($data['body']??'',500);$photoId=max(0,(int)($data['photoId']??0));if($photoId<=0)throw new InvalidArgumentException('Choisissez une photo de votre galerie.');$photo=phone_stmt($db,'SELECT id,url FROM camera_photos WHERE id=? AND user_id=? LIMIT 1','ii',[$photoId,$userId])->get_result()->fetch_assoc();if(!$photo)phone_json(['ok'=>false,'error'=>'Cette photo n’appartient pas à votre galerie.'],403);phone_stmt($db,'INSERT INTO phone_gram_posts(user_id,body,image_url,created_at) VALUES(?,?,?,?)','issi',[$userId,$body,$photo['url'],$now]);phone_json(['ok'=>true]);}
  if($op==='delete_comment'){$commentId=max(0,(int)($data['commentId']??0));$c=phone_stmt($db,'SELECT user_id FROM phone_gram_comments WHERE id=? LIMIT 1','i',[$commentId])->get_result()->fetch_assoc();if(!$c)phone_json(['ok'=>false,'error'=>'Commentaire introuvable.'],404);if((int)$c['user_id']!==$userId)phone_json(['ok'=>false,'error'=>'Suppression refusée.'],403);phone_stmt($db,'DELETE FROM phone_gram_comments WHERE id=? AND user_id=?','ii',[$commentId,$userId]);phone_json(['ok'=>true]);}
  if($op==='follow'){$target=max(0,(int)($data['targetUserId']??0));if($target<=0||$target===$userId)throw new InvalidArgumentException('Abonnement invalide.');$exists=phone_stmt($db,'SELECT id FROM users WHERE id=? LIMIT 1','i',[$target])->get_result()->fetch_assoc();if(!$exists)phone_json(['ok'=>false,'error'=>'Utilisateur introuvable.'],404);$f=phone_stmt($db,'SELECT 1 FROM phone_gram_follows WHERE follower_id=? AND following_id=?','ii',[$userId,$target])->get_result()->fetch_row();if($f)phone_stmt($db,'DELETE FROM phone_gram_follows WHERE follower_id=? AND following_id=?','ii',[$userId,$target]);else{phone_stmt($db,'INSERT INTO phone_gram_follows(follower_id,following_id,created_at) VALUES(?,?,?)','iii',[$userId,$target,$now]);phone_stmt($db,"INSERT INTO phone_gram_notifications(user_id,actor_id,type,post_id,created_at) VALUES(?,?,'follow',NULL,?)",'iii',[$target,$userId,$now]);}phone_json(['ok'=>true,'following'=>!$f]);}
  $post=phone_stmt($db,'SELECT id,user_id FROM phone_gram_posts WHERE id=? LIMIT 1','i',[$postId])->get_result()->fetch_assoc();if(!$post)phone_json(['ok'=>false,'error'=>'Publication introuvable.'],404);
  if($op==='like'){$liked=phone_stmt($db,'SELECT 1 FROM phone_gram_likes WHERE post_id=? AND user_id=?','ii',[$postId,$userId])->get_result()->fetch_row();if($liked)phone_stmt($db,'DELETE FROM phone_gram_likes WHERE post_id=? AND user_id=?','ii',[$postId,$userId]);else{phone_stmt($db,'INSERT INTO phone_gram_likes(post_id,user_id,created_at) VALUES(?,?,?)','iii',[$postId,$userId,$now]);if((int)$post['user_id']!==$userId)phone_stmt($db,"INSERT INTO phone_gram_notifications(user_id,actor_id,type,post_id,created_at) VALUES(?,?,'like',?,?)",'iiii',[(int)$post['user_id'],$userId,$postId,$now]);}phone_json(['ok'=>true,'liked'=>!$liked]);}
  if($op==='comment'){$body=phone_text($data['body']??'',240,true);phone_stmt($db,'INSERT INTO phone_gram_comments(post_id,user_id,body,created_at) VALUES(?,?,?,?)','iisi',[$postId,$userId,$body,$now]);if((int)$post['user_id']!==$userId)phone_stmt($db,"INSERT INTO phone_gram_notifications(user_id,actor_id,type,post_id,created_at) VALUES(?,?,'comment',?,?)",'iiii',[(int)$post['user_id'],$userId,$postId,$now]);phone_json(['ok'=>true]);}
  if($op==='delete'){if((int)$post['user_id']!==$userId)phone_json(['ok'=>false,'error'=>'Suppression refusée.'],403);$db->begin_transaction();try{phone_stmt($db,'DELETE FROM phone_gram_notifications WHERE post_id=?','i',[$postId]);phone_stmt($db,'DELETE FROM phone_gram_comments WHERE post_id=?','i',[$postId]);phone_stmt($db,'DELETE FROM phone_gram_likes WHERE post_id=?','i',[$postId]);phone_stmt($db,'DELETE FROM phone_gram_posts WHERE id=? AND user_id=?','ii',[$postId,$userId]);$db->commit();}catch(Throwable $error){$db->rollback();throw $error;}phone_json(['ok'=>true]);}
  phone_json(['ok'=>false,'error'=>'Action inconnue.'],404);
}catch(InvalidArgumentException $error){phone_json(['ok'=>false,'error'=>$error->getMessage()],422);}catch(Throwable $error){error_log('[Paradise Phone API] '.$error->getMessage());phone_json(['ok'=>false,'error'=>'Impossible de charger cette application.'],500);}
