<?php
class AdminService {
    private mysqli $db;
    private array $actor;
    public function __construct(mysqli $db, array $actor){$this->db=$db;$this->actor=$actor;}
    public function rank(): int{return (int)$this->actor['rank'];}
    public function requireRank(int $rank): void{if($this->rank()<$rank){http_response_code(403);throw new RuntimeException('Ton grade ne permet pas cette action.');}}
    public function query(string $sql,string $types='',array $params=[]): mysqli_result|bool{$s=$this->db->prepare($sql);if(!$s)throw new RuntimeException('Requête invalide.');if($types!=='')$s->bind_param($types,...$params);$s->execute();$r=$s->get_result();return $r?:true;}
    public function one(string $sql,string $types='',array $params=[]): ?array{$r=$this->query($sql,$types,$params);return $r instanceof mysqli_result?($r->fetch_assoc()?:null):null;}
    public function log(string $action,string $targetType='',string $targetId='',array $details=[]):void{$json=json_encode($details,JSON_UNESCAPED_UNICODE);$ip=AppFunctions::GetIP();$now=time();$id=(int)$this->actor['id'];$this->query('INSERT INTO cms_audit_log(actor_id,action,target_type,target_id,context_json,ip_address,created_at) VALUES(?,?,?,?,?,?,?)','isssssi',[$id,$action,$targetType,$targetId,$json,$ip,$now]);}
    public function user(string $value):?array{$field=ctype_digit($value)?'u.id':'u.username';return $this->one("SELECT u.*,pg.name rank_name,p.level,p.bank,p.curhealth,p.maxhealth,p.is_jailed,p.jailed_time_left,p.corp,p.gang,p.arrests,p.kills,p.deaths,s.OnlineTime,s.Respect FROM users u LEFT JOIN permissions_groups pg ON pg.id=u.rank LEFT JOIN play_stats p ON p.id=u.id LEFT JOIN user_stats s ON s.id=u.id WHERE $field=? LIMIT 1",ctype_digit($value)?'i':'s',[ctype_digit($value)?(int)$value:$value]);}
    public function activeBan(int $uid):?array{return $this->one("SELECT b.*,b.type bantype,b.ban_reason reason,b.ban_expire expire,COALESCE(s.username,'Systeme') added_by,b.timestamp added_date FROM bans b LEFT JOIN users s ON s.id=b.user_staff_id WHERE b.user_id=? AND b.type IN ('account','super') AND (b.ban_expire=0 OR b.ban_expire>?) ORDER BY b.id DESC LIMIT 1",'ii',[$uid,time()]);}
    public function ban(array $user,string $reason,int $hours,bool $permanent=false,string $type='account'):void{$this->requireRank(4);if((int)$user['rank']>=$this->rank())throw new RuntimeException('Tu ne peux pas sanctionner un grade égal ou supérieur au tien.');$expire=$permanent?0:time()+max(1,$hours)*3600;$value=$type==='ip'?(string)$user['ip_last']:(string)$user['username'];$uid=(int)$user['id'];$by=(string)$this->actor['username'];$date=(string)time();$this->query('DELETE FROM bans WHERE user_id=? AND bantype=?','is',[$uid,$type]);$this->query('INSERT INTO bans(user_id,bantype,value,reason,expire,added_by,added_date) VALUES(?,?,?,?,?,?,?)','isssiss',[$uid,$type,$value,$reason,$expire,$by,$date]);$this->log('ban.create','user',(string)$uid,['type'=>$type,'reason'=>$reason,'expire'=>$expire]);}
    public function unban(int $uid,string $type='account'):void{$this->requireRank(4);$this->query('DELETE FROM bans WHERE user_id=? AND type=?','is',[$uid,$type]);$this->log('ban.remove','user',(string)$uid,['type'=>$type]);}
    public function updateEconomy(array $user,int $credits,int $duckets,int $diamonds,int $bank):void{$this->requireRank(5);$uid=(int)$user['id'];$old=['credits'=>(int)$user['credits'],'duckets'=>(int)$user['activity_points'],'diamonds'=>(int)$user['vip_points'],'bank'=>(int)$user['bank']];$this->query('UPDATE users SET credits=?,activity_points=?,vip_points=? WHERE id=?','iiii',[max(0,$credits),max(0,$duckets),max(0,$diamonds),$uid]);$this->query('UPDATE play_stats SET bank=? WHERE id=?','ii',[max(0,$bank),$uid]);$this->log('economy.update','user',(string)$uid,['before'=>$old,'after'=>compact('credits','duckets','diamonds','bank')]);}
    public function updateIdentity(array $user,string $motto,string $look,int $rank):void{$this->requireRank(5);$uid=(int)$user['id'];if($rank!==(int)$user['rank']){$this->requireRank(6);if($rank>=$this->rank())throw new RuntimeException('Tu ne peux pas attribuer ton propre grade ou un grade supérieur.');}$this->query('UPDATE users SET motto=?,look=?,rank=? WHERE id=?','ssii',[substr($motto,0,50),substr($look,0,255),$rank,$uid]);$this->log('user.update','user',(string)$uid,['rank_before'=>(int)$user['rank'],'rank_after'=>$rank]);}
    public function jail(array $user,int $minutes,bool $release=false):void{$this->requireRank(4);$uid=(int)$user['id'];$jailed=$release?'0':'1';$seconds=$release?0:max(1,$minutes)*60;$this->query('UPDATE play_stats SET is_jailed=?,jailed_time_left=? WHERE id=?','sii',[$jailed,$seconds,$uid]);$this->log($release?'rp.jail.release':'rp.jail.create','user',(string)$uid,['minutes'=>$minutes]);}
}
