<?php
class ShopService {
 private mysqli $db;public function __construct(mysqli $db){$this->db=$db;}
 private function stmt(string $sql,string $types='',array $params=[]):mysqli_stmt{$s=$this->db->prepare($sql);if(!$s)throw new RuntimeException('Requête boutique invalide.');if($types)$s->bind_param($types,...$params);$s->execute();return $s;}
 public function categories():mysqli_result{return $this->db->query("SELECT c.*,COUNT(p.id) products FROM cms_shop_categories c LEFT JOIN cms_shop_products p ON p.category_id=c.id AND p.active=1 WHERE c.active=1 GROUP BY c.id ORDER BY c.display_order,c.name");}
 public function products(int $category=0):mysqli_result{$where=$category?' AND p.category_id=?':'';$sql="SELECT p.*,c.name category_name,IF(p.sale_price IS NOT NULL AND p.sale_start<=? AND p.sale_end>=?,p.sale_price,p.price) current_price FROM cms_shop_products p JOIN cms_shop_categories c ON c.id=p.category_id WHERE p.active=1 AND c.active=1$where ORDER BY p.featured DESC,p.id DESC";return $category?$this->stmt($sql,'iii',[time(),time(),$category])->get_result():$this->stmt($sql,'ii',[time(),time()])->get_result();}
 public function history(int $uid):mysqli_result{return $this->stmt("SELECT * FROM cms_shop_orders WHERE user_id=? ORDER BY id DESC LIMIT 30",'i',[$uid])->get_result();}
 public function buy(int $uid,int $productId,string $token):array{if(!preg_match('/^[a-f0-9]{32}$/',$token))throw new RuntimeException('Requête d’achat invalide.');$this->db->begin_transaction();try{$dup=$this->stmt('SELECT id FROM cms_shop_orders WHERE request_token=? FOR UPDATE','s',[$token])->get_result()->fetch_assoc();if($dup)throw new RuntimeException('Cet achat a déjà été traité.');$p=$this->stmt("SELECT *,IF(sale_price IS NOT NULL AND sale_start<=? AND sale_end>=?,sale_price,price) current_price FROM cms_shop_products WHERE id=? AND active=1 FOR UPDATE",'iii',[time(),time(),$productId])->get_result()->fetch_assoc();if(!$p)throw new RuntimeException('Produit indisponible.');if($p['stock']!==null&&(int)$p['stock']<=0)throw new RuntimeException('Produit épuisé.');if($p['per_user_limit']!==null){$n=$this->stmt("SELECT COUNT(*) n FROM cms_shop_orders WHERE user_id=? AND product_id=? AND status='completed'",'ii',[$uid,$productId])->get_result()->fetch_assoc();if((int)$n['n']>=(int)$p['per_user_limit'])throw new RuntimeException('Limite d’achat atteinte.');}$u=$this->stmt('SELECT credits,activity_points,vip_points,rank_vip,vip_expire FROM users WHERE id=? FOR UPDATE','i',[$uid])->get_result()->fetch_assoc();if(!$u)throw new RuntimeException('Compte introuvable.');$columns=['credits'=>'credits','duckets'=>'activity_points','diamonds'=>'vip_points'];$col=$columns[$p['currency']];$price=(int)$p['current_price'];if((int)$u[$col]<$price)throw new RuntimeException('Solde insuffisant.');$this->db->query("UPDATE users SET $col=$col-$price WHERE id=".(int)$uid);$rewardColumns=['credits'=>'credits','duckets'=>'activity_points','diamonds'=>'vip_points'];if(isset($rewardColumns[$p['reward_type']])){$rc=$rewardColumns[$p['reward_type']];$this->db->query("UPDATE users SET $rc=$rc+".(int)$p['reward_amount']." WHERE id=".(int)$uid);}elseif($p['reward_type']==='vip'){$expire=max(time(),(int)$u['vip_expire'])+max(1,(int)$p['duration_days'])*86400;$this->stmt('UPDATE users SET rank_vip=?,vip_expire=? WHERE id=?','iii',[(int)$p['reward_amount'],$expire,$uid]);}else throw new RuntimeException('Récompense incompatible.');if($p['stock']!==null)$this->stmt('UPDATE cms_shop_products SET stock=stock-1 WHERE id=?','i',[$productId]);$now=time();$this->stmt("INSERT INTO cms_shop_orders(request_token,user_id,product_id,product_name,price,currency,reward_type,reward_amount,status,created_at) VALUES(?,?,?,?,?,?,?,?,'completed',?)",'siisissii',[$token,$uid,$productId,$p['name'],$price,$p['currency'],$p['reward_type'],(int)$p['reward_amount'],$now]);$this->db->commit();return ['product'=>$p['name'],'price'=>$price,'currency'=>$p['currency']];}catch(Throwable $e){$this->db->rollback();throw $e;}}
}
